# Name, title and description
name: Jared Einstein
title: live and learn
description: every day

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:title.html
  recipes_categories:
    output: true
    permalink: /recipes/category/:title.html
  quotes:
    output: false
  kiddies:
    output: false
  posts:
    permalink: /blog/:year/:month/:day/:title.html
    
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
  -
    scope:
      path: ""
      type: "recipes_categories"
    values:
      layout: "recipes_category"
  -
    scope:
      path: ""
      type: "quotes"
  -
    scope:
      path: ""
      type: "kiddies"
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "assets/img"
    values:
      image: true
  -
    scope:
      path: "assets/img/recipes"
    values:
      img_recipe: true

# include the _pages directory
include: ['_pages']

# Includes an icon in the footer for each username entered
footer-links:
  dribbble:
  email: #jared.einstein@gmail.com
  facebook:
  flickr:
  github: jaredeinstein/jaredeinstein.github.io
  instagram: notcoachjerry
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: jaredeinstein
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: channel/UC-O5wwl41LHOueSFA7QCIcA # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  
# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
# url: https://jaredeinstein.github.io   changed to CNAME on 180215 1425
url: https://jared.einsteinstudios.net

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Jekyll theme
theme: jekyll-theme-cayman

permalink: /:year/:month/:day/:title.html

# defaults for front matter
# https://jekyllrb.com/docs/configuration/#front-matter-defaults


# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  
# Markdown type
markdown: kramdown
